services:
  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=app
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=app
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
      - TZ=Asia/Tokyo
    depends_on:
      - database
    volumes:
      - ./:/go/app:rw
    ports:
      - "80:8080"
